template-file-path: ./iam-automation.yaml

stack-name: iam-automation-demo

region: us-east-1

capabilities:
  - CAPABILITY_NAMED_IAM

parameters:
  PasswordLength: 16

tags:
  Project: BEM11-IAM-Lab
  Environment: Lab
  ManagedBy: GitSync-CloudFormation
  